- name: copy files
  become: true
  become_user: "{{ deploy_user }}"
  synchronize: src=../../../../ dest={{ deploy_directory }} delete=yes rsync_opts=--exclude=.git/,--exclude=log/,--exclude=tmp/,--exclude=node_modules/,--exclude=ops/

- name: install packages based on package.json
  become: true
  become_user: "{{ deploy_user }}"
  shell: npm install
  args:
    chdir: "{{ deploy_directory }}"

- name: setup cron
  become: true
  become_user: "{{ deploy_user }}"
  cron: name="{{ app_name }} - Job {{ item.0 }}" minute="0" hour="{{ item.1.cron_hour }}"
    job="/bin/bash -l -c 'cd {{ deploy_directory }} && {{ app_cmd }} {{ item.1.app_args }}' >> {{ log_file }}"
  with_indexed_items: "{{ cron_jobs }}"

